events {}

http {
  resolver 127.0.0.11 valid=10s ipv6=off;

  server {
    listen 80;
    server_name _;

    set $wtc_backend wall-thickness-compensation-backend:8000;
    set $wtc_frontend wall-thickness-compensation-frontend:80;

    location /api/wall-thickness-compensation/ {
      rewrite ^/api/wall-thickness-compensation/(.*)$ /$1 break;
      proxy_pass http://$wtc_backend;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      client_max_body_size 128m;
    }

    location /health {
      proxy_pass http://$wtc_backend/health;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
      proxy_pass http://$wtc_frontend;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}
